### PR TITLE
	Linted main file with standard

### PR DESCRIPTION
**Pull request by HugoGiraudel**

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Or do we want to avoid the dev dep here?

**Comment by pascalduez** [comment]
I might be beyond the scope of this package.  
Also wondering about forcing "our" style for boilerplates?

**Comment by valeriangalliat** [comment]
Yea, not sure about forcing `standard` here, but I mean, I think it's good practice to use it nowdays so why not. And it can still be easily removed anyway.

**Comment by HugoGiraudel** [comment]
I think we should move code linting to standard but not add standard dependency. I’ll update the PR.

**Pull request merged**
